export const COUNTRY_CODES = [
    { code: "+1", flag: "🇺🇸", label: "United States" },
    { code: "+7", flag: "🇷🇺", label: "Russia" },
    { code: "+20", flag: "🇪🇬", label: "Egypt" },
    { code: "+27", flag: "🇿🇦", label: "South Africa" },
    { code: "+30", flag: "🇬🇷", label: "Greece" },
    { code: "+31", flag: "🇳🇱", label: "Netherlands" },
    { code: "+32", flag: "🇧🇪", label: "Belgium" },
    { code: "+33", flag: "🇫🇷", label: "France" },
    { code: "+34", flag: "🇪🇸", label: "Spain" },
    { code: "+36", flag: "🇭🇺", label: "Hungary" },
    { code: "+39", flag: "🇮🇹", label: "Italy" },
    { code: "+41", flag: "🇨🇭", label: "Switzerland" },
    { code: "+43", flag: "🇦🇹", label: "Austria" },
    { code: "+44", flag: "🇬🇧", label: "United Kingdom" },
    { code: "+45", flag: "🇩🇰", label: "Denmark" },
    { code: "+46", flag: "🇸🇪", label: "Sweden" },
    { code: "+47", flag: "🇳🇴", label: "Norway" },
    { code: "+48", flag: "🇵🇱", label: "Poland" },
    { code: "+49", flag: "🇩🇪", label: "Germany" },

    { code: "+60", flag: "🇲🇾", label: "Malaysia" },
    { code: "+61", flag: "🇦🇺", label: "Australia" },
    { code: "+62", flag: "🇮🇩", label: "Indonesia" },
    { code: "+63", flag: "🇵🇭", label: "Philippines" },
    { code: "+64", flag: "🇳🇿", label: "New Zealand" },
    { code: "+65", flag: "🇸🇬", label: "Singapore" },
    { code: "+66", flag: "🇹🇭", label: "Thailand" },

    { code: "+81", flag: "🇯🇵", label: "Japan" },
    { code: "+82", flag: "🇰🇷", label: "South Korea" },
    { code: "+84", flag: "🇻🇳", label: "Vietnam" },
    { code: "+86", flag: "🇨🇳", label: "China" },

    { code: "+90", flag: "🇹🇷", label: "Turkey" },
    { code: "+91", flag: "🇮🇳", label: "India" },
    { code: "+92", flag: "🇵🇰", label: "Pakistan" },
    { code: "+93", flag: "🇦🇫", label: "Afghanistan" },
    { code: "+94", flag: "🇱🇰", label: "Sri Lanka" },
    { code: "+95", flag: "🇲🇲", label: "Myanmar" },
    { code: "+98", flag: "🇮🇷", label: "Iran" },

    { code: "+211", flag: "🇸🇸", label: "South Sudan" },
    { code: "+212", flag: "🇲🇦", label: "Morocco" },
    { code: "+213", flag: "🇩🇿", label: "Algeria" },
    { code: "+216", flag: "🇹🇳", label: "Tunisia" },
    { code: "+218", flag: "🇱🇾", label: "Libya" },
    { code: "+220", flag: "🇬🇲", label: "Gambia" },
    { code: "+221", flag: "🇸🇳", label: "Senegal" },
    { code: "+222", flag: "🇲🇷", label: "Mauritania" },
    { code: "+223", flag: "🇲🇱", label: "Mali" },
    { code: "+224", flag: "🇬🇳", label: "Guinea" },
    { code: "+225", flag: "🇨🇮", label: "Ivory Coast" },
    { code: "+226", flag: "🇧🇫", label: "Burkina Faso" },
    { code: "+227", flag: "🇳🇪", label: "Niger" },
    { code: "+228", flag: "🇹🇬", label: "Togo" },
    { code: "+229", flag: "🇧🇯", label: "Benin" },

    { code: "+233", flag: "🇬🇭", label: "Ghana" },
    { code: "+234", flag: "🇳🇬", label: "Nigeria" },
    { code: "+235", flag: "🇹🇩", label: "Chad" },
    { code: "+236", flag: "🇨🇫", label: "Central African Republic" },
    { code: "+237", flag: "🇨🇲", label: "Cameroon" },
    { code: "+249", flag: "🇸🇩", label: "Sudan" },
    { code: "+250", flag: "🇷🇼", label: "Rwanda" },
    { code: "+251", flag: "🇪🇹", label: "Ethiopia" },
    { code: "+252", flag: "🇸🇴", label: "Somalia" },
    { code: "+253", flag: "🇩🇯", label: "Djibouti" },
    { code: "+254", flag: "🇰🇪", label: "Kenya" },
    { code: "+255", flag: "🇹🇿", label: "Tanzania" },
    { code: "+256", flag: "🇺🇬", label: "Uganda" },
    { code: "+257", flag: "🇧🇮", label: "Burundi" },
    { code: "+260", flag: "🇿🇲", label: "Zambia" },
    { code: "+263", flag: "🇿🇼", label: "Zimbabwe" },
];